### ISSUE TITLE
1.7.0 artifacts not published to maven servers - generate command fails

### ISSUE THREAD

**Issue by kworth** [mParticle/smartype#57]
We appear to be having an issue running `mvnx com.mparticle:smartype-generator generate` and it seems possible it may be due to the fact that the various 1.7.0 dependencies have not been published.

#### smartype-mparticle up to 1.6.2 only

- https://mvnrepository.com/artifact/com.mparticle/smartype-mparticle
- https://central.sonatype.com/artifact/com.mparticle/smartype-mparticle/versions
 
#### smartype-api up to 1.6.2 only

- https://mvnrepository.com/artifact/com.mparticle/smartype-api
- https://central.sonatype.com/artifact/com.mparticle/smartype-api/versions

### Error Output

```
* What went wrong:
Execution failed for task ':smartype:compileReleaseKotlinAndroid'.
> Could not resolve all files for configuration ':smartype:releaseCompileClasspath'.
   > Could not find com.mparticle:smartype-mparticle:1.7.0.
     Required by:
         project :smartype
   > Could not find com.mparticle:smartype-api:1.7.0.
     Required by:
         project :smartype
```

**Comment by samdozor** [comment]
hi @kworth! ack'ing your issue and having a look now - indeed seems like those artifacts didn't get pushed. will revert back asap.

**Comment by kevin-worth-sk** [comment]
1.7.1 artifacts are now published to the sonatype.com maven servers.

EDIT: and now the mvnrepository.com servers as well.
